### ISSUE TITLE
Error when creating meta data on ssocircle

### ISSUE THREAD

**Issue by nWidart** [taiyeoguns/laravel-saml-sp-demo#1]
Hello,

I'm following your steps regarding sso circle setup.

However when submitting the form with the data it says the following:

```

Error occurred


Reason: A http://localhost:8000/saml2/metadata entity already exists. Go to the *Manage Metadata*, and delete the existing http://localhost:8000/saml2/metadata entity first.

Detailed trace information only available with paid accounts.
Please check our plans
 
```

Yet when I go into the meta data page, it only displays this:

```
	Service Provider Metadata
You currently do not have Service Provider Metadata
Add new Service Provider

SSOCircle Public IDP Metadata

SSOCircle Public IDP Metadata (deprecated)
```

Any idea what I'm doing wrong ? 

Thanks!

**Comment by taiyeoguns** [comment]
Hi @nWidart, 

The URL on SSOCircle where I added the metadata is:

https://idp.ssocircle.com/sso/hos/ManageSPMetadata.jsp

If the issue persists, I suppose there may be a name clash of some sort internally within SSOCircle, though I expect different users should be able to register same urls for service providers.

You could try a tunneling service like [ngrok](https://ngrok.com/) pointing to your localhost then use the tunnel URL on SSOCircle

**Comment by nWidart** [comment]
Thank you for your prompt reply.

Indeed I suspect something similar. Especially since I was able to login (locally), without added the meta data.
It's odd that it can only have one of those names for _all_ across users.

Thank you for this demo, very useful! 👍

**Comment by taiyeoguns** [comment]
Glad I can be of help.

Please let me know how it goes. May have to modify the readme to take that into account.

**Comment by srinuydlp** [comment]
how metadata file looks like in struts application, is it xml or .md extention file
