### ISSUE TITLE
custom attributes against ADFS 3.0

### ISSUE THREAD

**Issue by pet1330** [taiyeoguns/laravel-saml-sp-demo#2]
Hi,

Thank you for putting together this demo, it has been really useful to learn how SAML authenticating works. I am currently adapting this project to authenticate against another idp which uses ADFS 3.0. 

I am able to reach the idp login form, but when I am directed back after authenticating successful, I am sent to the `error` url. I am also not able to get any user attributes. I think this might be because I'm requesting firstName, lastName and emailAddress which will be labelled differently on our idp.

How can I configure which information I request from the idp?

For example, if I wanted to get the users nickname, or manager, how could I request these attributes instead of firstName, lastName, emailAddress?

Thanks

**Comment by pet1330** [comment]
As it turns out, I was given the wrong certificate by ICT and the user attributes are set by the idp, not our application.

**Comment by taiyeoguns** [comment]
Hi @pet1330 ,

The assertion attributes are configured and sent by the IdP. In this case, 'firstName', 'lastName and 'emailAddress' are sent by SSOCircle

Glad you figured it out eventually.
