### ISSUE TITLE
login user question

### ISSUE THREAD

**Issue by enricouniurb** [taiyeoguns/laravel-saml-sp-demo#5]
Is possible in LoginListener.php
avoid to save the user? and already have the authentication?

Thank you in advance 
Enrico

**Comment by taiyeoguns** [comment]
Hi @enricouniurb,

You would have the authentication successful on the IdP but not in the Laravel application. 

The LoginListener just waits for event fired from the IdP response and receives the assertion attributes (in this case email, firstName, lastName).

Depending on your use case, you can use these attributes to authenticate some other way if you don't want to save the user.
