### ISSUE TITLE
Use with Laravel 5.6

### ISSUE THREAD

**Issue by leoleylan** [taiyeoguns/laravel-saml-sp-demo#6]
Dear @taiyeoguns,

first off, thanks for your great work!

I have an issue with the listener (I believe) and I think it has to do with my Laravel version as it seems there have been some changes in the recent Laravel versions. It doesn't seem to "fire" after logging in.
Do you know what I have to do? I don't find anything regarding the SAML login in my session. But it seems the SAML-auth itself is working.

Maybe I have missed something? If I try to implement this into an existing application, what all do I have to "copy"? I have the controller, the middleware, the listener and the routes.

Thanks again!
Curtis

**Comment by taiyeoguns** [comment]
Hi @goodcurtis,

Thanks. Do you get a redirect to your Laravel application after logging in at the IdP?

I would suggest to check the logs and the browser developer console. Check that the events and listeners are registered like in the `EventServiceProvider.php`

Verify also that the settings provided for the plugin in `config/saml2_settings.php` are accurate (such as `loginRoute`).

To use in an existing application, I suppose the [Plugin Install & Configuration](https://github.com/aacotroneo/laravel-saml2), Controller, Provider, Middleware, Listeners, Routes should be sufficient.

**Comment by goodcurtis** [comment]
_Thanks. Do you get a redirect to your Laravel application after logging in at the IdP?_
Yes I did get a redirect. What does that show me?

_I would suggest to check the logs and the browser developer console. Check that the events and listeners are registered like in the EventServiceProvider.php_
The logs don't show anything and my EventServiceProvider.php looks just like yours. Am I missing something here maybe?

It looks like everything is working well regarding the login/redirect flow, but I don't find anything that should have been fired from the LoginListener (Name/ID in Session or new user in DB. Dumping all session data to check). Pretty sure saml_settings.php is ok.

Thanks for your help!

**Comment by taiyeoguns** [comment]
The redirect was to check that the SAML flow is going through properly.

Other thing you could check is if the event/listener is working. In the `LoginListener.php`, try writing any events to the log, e.g.

```php
public function handle(Saml2LoginEvent $event)
{
	\Log::info($event);
	
	//or
	
	//\Log::info('I got fired');
}
```

then perform the flow again and check in the logs if anything is written.

If you get an entry in the logs, then the events are working. Next will be to check the attributes from the IdP. Are you using SSOCircle as well? If so, check the assertion attributes were selected.

If I get some time, I can try to do a version with Laravel 5.6

**Comment by goodcurtis** [comment]
Hi @taiyeoguns,

it seems like the event is not fired as there's nothing being logged and I am wondering if this is due to changes in Laravel from 5.4 to 5.6. Do you have any idea about this?

Thank you!

**Comment by RameshK3** [comment]
Hi, Even im facing the same issue in version 5.5... Successfully authenticating but redirecting SP url, event is not trigerred.. The same is working in version 5.4... Seems issue in laravel versions. can u pls help us...,

**Comment by taiyeoguns** [comment]
I did the demo with latest Laravel 5.5 & 5.6 versions using SSOCircle IdP and did not have any issues with the events. Everything worked fine for me.

If you don't get the login event fired, it could be that the request after redirect from the IdP is not getting to the `acs` route of the plugin:

- The [login event is fired](https://github.com/aacotroneo/laravel-saml2/blob/ef6e5b32f1f861d80dde1442ebe1a2951a3824c7/src/Aacotroneo/Saml2/Http/Controllers/Saml2Controller.php#L55)   from the [`acs` method](https://github.com/aacotroneo/laravel-saml2/blob/ef6e5b32f1f861d80dde1442ebe1a2951a3824c7/src/Aacotroneo/Saml2/Http/Controllers/Saml2Controller.php#L41) of the plugin's controller
- Note that the `acs` route's HTTP [method](https://github.com/aacotroneo/laravel-saml2/blob/ef6e5b32f1f861d80dde1442ebe1a2951a3824c7/src/routes.php#L24) is **POST** and usually in Laravel this requires a csrf token but as the IdP is not likely to send a token in the redirect, you can exempt that route which I did in [VerifyCsrfToken.php](https://github.com/taiyeoguns/laravel-saml-sp-demo/blob/05b0c8cc1defad0c93a7753cd5fb39a8b96a6d73/app/Http/Middleware/VerifyCsrfToken.php#L16)
- You may also want to check with setting [`strict`](https://github.com/aacotroneo/laravel-saml2/blob/ef6e5b32f1f861d80dde1442ebe1a2951a3824c7/src/config/saml2_settings.php#L64) to `false` in the `saml_settings.php`

**Comment by RameshK3** [comment]
No luck.. event is not triggering.. @goodcurtis have u tried? is working?
