### ISSUE TITLE
Redirect to different URL

### ISSUE THREAD

**Issue by sospcie** [taiyeoguns/laravel-saml-sp-demo#7]
Hello, while this is an old repo, it is really great. It helped me a lot. However, one thing I am not able to figure out. If user is not logged in, and visit a specific page of my site, It will get redirected to the login, however after succesful login, they will be redirected to the route defined in the saml2_settings. How I can redirect to the original url they have visited before being redirected to the login?

**Comment by sospcie** [comment]
Ok, I think I have found one way to do it.

In saml2_settings.php just under $idp_host, I have added the following line:

`$loginRedirect = $_SERVER['HTTP_REFERER'];`

Then in the settings array, I have changed the loginRoute to the following:

`'loginRoute' => $loginRedirect,`

I tested and works perfectly, however most likely there are better way to do this.

If anyone know better way, please let me know.

**Comment by taiyeoguns** [comment]
Hi, sorry for the late reply.

Not tried but I suppose something like:

```php
'loginRoute' => redirect()->intended('home'),
```

should also work.
